pipeline {
  agent {
    label 'terraform'
  }

  stages {
    stage('Terraform Init') {
      steps {
        sh 'cd cloudflare/zone_vrsf.in && terraform init'
      }
    }

    stage('Terraform Plan') {
      steps {
        sh 'cd cloudflare/zone_vrsf.in && terraform plan'
      }
    }

    stage('Terraform Apply') {
      steps {
        sh 'cd cloudflare/zone_vrsf.in && terraform apply -auto-approve'
      }
    }

  }
}
